### ISSUE TITLE
Release jar 2.9.3 not compatible with jre6

### ISSUE THREAD

**Issue by pietrygamat** [java-native/jssc#110]

**Comment by tresf** [comment]
Hmmm.. that may be my mistake.  I wasn't paying close attention to the JDK version we used.  I'll re-build it now and attach a copy here.

**Comment by tresf** [comment]
This one should be better.  We built the binary using Homebrew's version of Maven, which ignores the default Java version of the system.  Using `JAVA_HOME`, here's one that should be compatible with Java 6.

[jssc-2.9.3.jar.zip](https://github.com/java-native/jssc/files/6948245/jssc-2.9.3.jar.zip)

**Comment by tresf** [comment]
I've re-uploaded the release artifact: https://github.com/java-native/jssc/releases/tag/v2.9.3.  Please feel to re-open if you believe this is closed in error. :)

**Comment by pietrygamat** [comment]
[That ](https://github.com/java-native/jssc/issues/113#issuecomment-900508370) looks like a reference to this problem. I'll reopen.

**Comment by tresf** [comment]
> [That ](https://github.com/java-native/jssc/issues/113#issuecomment-900508370) looks like a reference to this problem. I'll reopen.

Can you please explain?  I don't understand how they are related?

**Comment by tresf** [comment]
Oh, I see the OP claims that the binaries were built with the wrong JDK.  That's odd, I'm pretty sure I rebuilt then with JDK8.  This time, @GMKennedy rebuilt them, hopefully they're ok now.

**Comment by tresf** [comment]
I've tested @GMKennedy's release with Java 1.6 and it works fine.  Closing.  Please use https://github.com/java-native/jssc/releases/tag/v2.9.4.
