### ISSUE TITLE
Native Library Loader version 2.3.6 is not release

### ISSUE THREAD

**Issue by BetterPHPer** [java-native/jssc#112]
there is no a v 2.3.6 at https://mvnrepository.com/artifact/org.scijava/native-lib-loader ,
however you update it from 2.3.5 to 2.3.6 at the newest version 2.9.3 release

**Comment by pietrygamat** [comment]
As of now, this dependency is pulled to jssc from https://mvnrepository.com/artifact/org.scijava/native-lib-loader?repo=scijava-public
Should work for most users as long as they are not behind corporate nexus that does not proxy this repository.

**Comment by a-hansen** [comment]
Same issue:

`Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.scijava:native-lib-loader:2.3.6.
  Searched in the following locations:
    - file:/C:/Users/Aaron/.m2/repository/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.pom
    - file:/C:/Users/Aaron/.m2/repository/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.jar
    - https://repo.maven.apache.org/maven2/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.pom
    - https://repo.maven.apache.org/maven2/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.jar
    - https://maven.mangoautomation.net/repository/ias-release/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.pom
    - https://maven.mangoautomation.net/repository/ias-release/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.jar
    - https://jitpack.io/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.pom
    - https://jitpack.io/org/scijava/native-lib-loader/2.3.6/native-lib-loader-2.3.6.jar
  Required by:
      project : > io.github.java-native:jssc:2.9.3`

How are you supposed to declare the repo with it?  This is my build.gradle:

`repositories {
    mavenLocal()
    mavenCentral()
    maven {
    	url 'https://maven.mangoautomation.net/repository/ias-release/'
    }
    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation 'com.github.iot-dsa:sdk-dslink-java:1.0.0'
    implementation 'com.infiniteautomation:modbus4j:3.0.5'
    implementation 'io.github.java-native:jssc:2.9.2'
}`

**Comment by tresf** [comment]
scijava [has released `native-lib-loader` 2.3.6 to Maven Central](https://github.com/scijava/native-lib-loader/pull/40#issuecomment-922616155).

https://mvnrepository.com/artifact/org.scijava/native-lib-loader/2.3.6
