### ISSUE TITLE
Complete release 2.9.5

### ISSUE THREAD

**Issue by pietrygamat** [java-native/jssc#142]
I have prepared the relase according to 
https://github.com/java-native/jssc/wiki/Publishing-a-Release

Before releasing to maven central, let's do some additional testing

Github pre-release with "fat" jar:
https://github.com/java-native/jssc/releases/tag/v2.9.5

Maven staging repo (add this to pom to test with newest version with maven):
```
<dependencies>
    <dependency>
        <groupId>io.github.java-native</groupId>
        <artifactId>jssc</artifactId>
        <version>2.9.5</version>
    </dependency>
</dependencies>
```

```
<repositories>
    <repository>
        <id>jssc-staging</id>
        <url>https://oss.sonatype.org/content/repositories/iogithubjava-native-1016</url>
    </repository>
</repositories>
```

Tasks to do
- [x] Update Release notes
- [x] Release from sonatype staging nexus to maven central

**Comment by pietrygamat** [comment]
@tresf please find some time to review the draft release, and if you are satisfied, promote it to full release on Github. I'll then push follow up with maven central.

**Comment by tresf** [comment]
@pietrygamat I'd be happy to real-world test the 2.9.5 version but I don't currently have a project using JSSC with Maven to test with.  Are you OK if I simply test the fat jars?

**Comment by pietrygamat** [comment]
@tresf of course. I do have maven projects for Windows and Linux so I am pretty confident about this part. It's the native libs vs OS architectures that kill my self esteem every time :D.

**Comment by tresf** [comment]
> 

Ok, I'll have Intel testing on real hardware done soon per another project https://github.com/qzind/tray/pull/1165 and report my findings.

**Comment by tresf** [comment]
> @tresf please find some time to review the draft release

In regards to the release description, the only feedback that I have is that it's slightly redundant to mention both a bug report and a pull request for a bulleted item, however, I will list several bug reports on a line to illustrate popularity for fixes or features that were requested multiple times or span a wider range of issues.

The rest looks great, thank you.

> > `Minor clarification in javadoc: #73 #119`
> > `                                ^--- I would probably just list the bug report in this instance.`

**Comment by tresf** [comment]
> > 
> 
> Ok, I'll have Intel testing on real hardware done soon per another project [qzind/tray#1165](https://github.com/qzind/tray/pull/1165) and report my findings.

Testing passed.

<img width="555" alt="image" src="https://github.com/java-native/jssc/assets/6345473/98fed27a-b421-4739-bfe0-3d44c3842164">
