### ISSUE TITLE
Exception when opening port

### ISSUE THREAD

**Issue by athach** [java-native/jssc#164]
Hello,
Thank you very much for your work and sharing it. 

I moved from 2.8.0 to 2.9.6 and now I get an exception when opening a port: "SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"."

I had a look inside the jar and there are slf4j files in there. Am I supposed to include something more?

Thanks

**Comment by pietrygamat** [comment]
This is the same as #76. It should not be a critical problem, so if it prevents you from opening port, please share more details / stack trace.

**Comment by athach** [comment]
Thank you. I included the library and the error message is gone. Before posting here I did try that but with a more recent version of slf4j and that did not work. Maybe you should make a note about this on the front page for other users.

**Comment by tresf** [comment]
> Thank you. I included the library and the error message is gone. Before posting here I did try that but with a more recent version of slf4j and that did not work. Maybe you should make a note about this on the front page for other users.

This will depend where you get the library.  On our downloads page, it should never appear however from Maven it will.  This is because Maven requires the transient dependencies to be resolved by the build system whereas our download should contain everything needed to use the library.

Where did you download it from?  If it was from our downloads area, that's a bug.

**Comment by athach** [comment]
It was downloaded from https://github.com/java-native/jssc/releases/tag/v2.9.6

**Comment by tresf** [comment]
@athach from my testing, this is not an Exception, but rather a benign message logged to stderr.  Here's my code:


```java
public class MainJssc {
    public static void main(String... args) {
        System.out.println(Arrays.toString(SerialPortList.getPortNames()));
    }
}
```

> This is the same as https://github.com/java-native/jssc/issues/76. It should not be a critical problem, so if it prevents you from opening port, please share more details / stack trace.

This seems to be accurate.  Here's my output:

```diff
- SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
- SLF4J: Defaulting to no-operation (NOP) logger implementation
- SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  [/dev/cu.Bluetooth-Incoming-Port, /dev/cu.wlan-debug, /dev/tty.Bluetooth-Incoming-Port, /dev/tty.wlan-debug]
```

No exceptions are thrown in this example.  I believe the long-term plan is to remove native-lib-loader as a project dependency which will remove the transient dependency on slf4j.   With regards to documenting this, we're welcome to recommendations on how to present this to the user on the project page.

**Comment by athach** [comment]
I am sorry. You are correct, it is not an exception.
