### ISSUE TITLE
Issue with serialPort.isOpened() on Windows 11 (not tried in other OS)

### ISSUE THREAD

**Issue by Gionni997** [java-native/jssc#166]
Hi everyone,

I'm working on a program that allows me to open a COM port and communicate with a device through the graphical interface. When I do it for the first time, everything works fine, but when I try to restart everything without closing the COM port, it tells me that the port is closed. When I print Port.isOpen, it prints false, even though it should actually be true because I haven't closed the port yet. From the variables I see portOpened = false, even though portName is = to the port previously selected.  I don't know if the problem is in the library or in my code

	`@Override
	public void open (){
		System.out.println("isOpen" + isOpen());
		if (!isOpen()) {
			try {
				port.openPort();
				port.setParams(serialPortComConfiguration.getBaudRate(), serialPortComConfiguration.getDataBits(), 
                                serialPortComConfiguration.getStopBits(), serialPortComConfiguration.getParity());
				System.out.println("porta aperta");
	
				// port.addEventListener(new PortListener(port));

			} catch (SerialPortException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  } else {
				System.out.println("La porta è già aperta");
			}}`

and

`@Override
	public boolean isOpen() {
		logDebug(TAG, "isOpen");
		if (port.isOpened()) {return true;}
		else {
		return false;}
	}`

In the terminal there is this:
isOpenfalse
<<debug>> SerialComBase: isOpen
jssc.SerialPortException: Port name - COM13; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:165)

**Comment by Gionni997** [comment]
The problem was not in the library but in my code, sorry :(

**Comment by tresf** [comment]
> The problem was not in the library but in my code, sorry :(

Thanks for the update!

**Comment by yuyongqianggeek** [comment]
> The problem was not in the library but in my code, sorry :(

can you tell me the problem in your code ,i have the same problem but i don't know why
