### ISSUE TITLE
cross compiled armhf binary will not work

### ISSUE THREAD

**Issue by bmhm** [java-native/jssc#26]
cross compiled armhf and armsf binaries won't load (i.e. `UnsatisfiedLinkError`).
If I compile on my raspberry pi (using `-DskipTests` because of #24), loading the library will just run fine.

I also set the toolchain to armv6 (instead of 5). Need to test native compilation with softfloat and 5 and combinations.

**Comment by tresf** [comment]
@bmhm I've asked for some help from @Vzor- whom has some Pi to test on.

**Comment by bmhm** [comment]
Let’s target this for the next release. If you cannot make it by then, just leave the arm-lib out and retarget this for `3.1.0` (new feature) or leave it in and target it for `3.0.1` (bugfix). ;-)

**Comment by tresf** [comment]
Losing arm is a pretty serious regression, this is in scope until we prove it's too difficult.  Waiting on @Vzor-.  He has a working build from Ubuntu 16.04 using the `gcc5` armhf cross-compiling toolchain.

**Comment by tresf** [comment]
> Let’s target this for the next release.

I see now you meant 3.0.0.  This isn't obvious from mobile.
