### ISSUE TITLE
Rework default packaging

### ISSUE THREAD

**Issue by bmhm** [java-native/jssc#31]
The default packaging should be changed, as discussed on Slack.

## Current situtation
The build will create 
* a default jar with machine-type classifier, containing only this native library.
* a "uber-jar" with precompiled libraries.

## Critique

* A jar with only one native library is rarely needed.
* Instead, a jar with all the other precompiled libaries, but only one-off/updated (selected arch)  would be much more helpful.
* The "uber-jar" should be the default jar, because it is what developers would expect.
* The warning that an assembly provides the default jar (no classifier) is irritating.
* At the moment, creating fat jars is quite complicated due to this implementation (See #21).

## Proposed Solution

* Replace the default jar with a jar containing all the precompiled libraries.
* Create an additional jar with the existing classifier which includes the one-off (updated) library for the selected system type.

**Comment by tresf** [comment]
> * Replace the default jar with a jar containing all the precompiled libraries.
> * Create an additional jar with the existing classifier which includes the one-off (updated) library for the selected system type.

Both of these were accomplished when maven was merged into master.  I think this is OK to close.
