### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#36]
@bmhm and others... any objection to bumping the version to `3.0.0` (`-SNAPSHOT`)?  It's currently `2.8.1-SNAPSHOT` (@scream3r's last release being `2.8.0`).

Reasoning... renumbering to `3.0.0` would help distinguish this release version and patches from its predecessors as well as help illustrate some fundamental changes in the build system and the platforms we support (e.g. dropping Mac PowerPC; dropping Mac 32-bit).

**Comment by bmhm** [comment]
Go ahead.

Please start with the snapshot suffix. It'll be removed from the release version.
