### ISSUE TITLE
Project rename proposal

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#5]
This is a proposal to rename the project from `java-simple-serial-connector` to something else.  There are natural downstream effects to this:
* Dependency name will change (e.g. Maven) affecting projects
* Namespace changes (unavoidable -- we don't own scream3r.org and the classes aren't properly namespaced anyway)

Upsides:
* Easier to find in a search engine
* Shorter `git clone` URL

**Comment by bmhm** [comment]
Dependency name does not need to change. Maven can set them independently from github URLs.
That said, I'd still like to change the maven group:artifact to `com.github.java-native:<new-project-name>`.

What we shouldn't use:
* jSerial (Windows only).
  see https://github.com/thibautd/JSerial
* JavaComm (already owned by oracle, unix only)
  see https://www.oracle.com/technetwork/java/index-jsp-141752.html
* jRxTx 
  see https://github.com/openmuc/jrxtx

Last project seems to be pretty advanced btw.

**Comment by tresf** [comment]
> Dependency name does not need to change. 

If there's a way to offer a hint to the old project that would be nice.

> Maven can set them independently from github URLs.

If you're suggesting we keep the old maven name with a potentially new project name, I think that'll be confusing.

>  group:artifact to `com.github.java-native:<new-project-name>`

Ok.

We can just keep `jssc` if everyone wants, or if we want something more unique we can do a few proposals.

**Comment by bmhm** [comment]
I re-read the requirements from sonar, and they suggest to use `io.github` as a prefix.

Also, I'd like to propose:

```
  groupId=io.github.java-native.jssc
  artifactId=jssc
```

… because we might have other artefacts in the same namespace. E.g. `artifactId=jssc-parent` etc.

**Comment by tresf** [comment]
`jssc` is probably the easiest and least confusing name.  Shall I proceed?

**Comment by bmhm** [comment]
Sure. While you're at it, change the project's `groupId` to `io.github.java-native.jssc`.

Rationale: As this project might have multiple jars or poms some day, they should have a common `groupId`.

That is:
```xml
  <groupId>io.github.java-native.jssc</groupId>
  <artifactId>jssc</artifactId>
```

At the moment it seems duplicated, but as said, in the future we might have multiple artefacts (like `jssc-parent` where all the profiles and version information is, `jssc-native` to separate the shared objects, `jssc-api` to separate API and Implementation some day, etc.).

**Comment by tresf** [comment]
> Sure. While you're at it, change the project's groupId to io.github.java-native.jssc.

Done, but did I mess it up?  https://github.com/java-native/java-simple-serial-connector/pull/18/commits/176f727bbd62866112222a502ad0bb35b83838c1#diff-865913557c5623f45eed23c4458032e7R21

The maven build now says:

```
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'io.github.java-native:jssc'
```

Should that be reverted?

**Comment by bmhm** [comment]
Fixed with:
* https://github.com/java-native/jssc/commit/fd267321f6b5ca2aea619e772e9d1e085f8d7ec0
* https://github.com/java-native/jssc/commit/bc17da0663d7fdf75993f097a85728cebface8de

Sorry for not mentioning this issue in the commit message.
