### ISSUE TITLE
arm tests use bundled library, not built library

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#51]
When compiling directly on arm (e.g. Raspberry Pi), it appears to run tests using the `.so` from the repo instead of the one that's built.  I can't get it to pass a test unless I hand-place the `.so` file in place.

**Edit:** Correction, when building directly on a Pi this occurs, not cross-compiling. That was a typo.

**Comment by tresf** [comment]
Correct, when building directly on a Pi this occurs, not cross-compiling.  That was a typo.

**Comment by pietrygamat** [comment]
This was fixed in #151 

https://github.com/java-native/jssc/pull/151/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR198-R199
