### ISSUE TITLE
Add NodeJS/Electron support

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#56]
Per request of @scream3r, the ability to abstract the native code and make the library re-usable for Electron/NodeJS support.

**Comment by bmhm** [comment]
The new build setup I am currently creating will create jar files which will only contain a single .so file. Optionally I can add the header and create other archive types. I'd it this which was requested?

**Comment by tresf** [comment]
I've never written an Electron native plugin before, but the various tutorials seem to all mention a `node-gyp` utility and often a `electron-rebuild` utility which matches Node.js modules to a Electron-compatible version.

Electron wouldn't need the Jar file specifically, so this task would likely be more of an API-abstracting (or API-Electron-JNI-wrapping) task rather than a request for other archive types.

**Comment by tresf** [comment]
I believe this effort it out of scope for this project.  Feel free to request a reopen if someone believes otherwise.
