### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#74]
Placeholder to support the new `aarch64` Apple M1 CPU.  Note, Intel Macs can cross-compile for `aarch64`, but any unit tests will require a physical ARM64 Mac.

**Comment by madskills700** [comment]
I have M1 air and some devices using rs232 and I could help.

**Comment by tresf** [comment]
@madskills700 it's almost ready, days and we'll have it published! :)

**Comment by tresf** [comment]
@madskills700 this should be ready: https://github.com/java-native/jssc/releases

It will be published to maven as soon as possible.
