### ISSUE TITLE
Make this library a Java module

### ISSUE THREAD

**Issue by muety** [java-native/jssc#79]
I wanted to use this library in modularized Java application, but, not surprisingly, am getting an error:

```
Package 'jssc' is declared in module 'jssc', but module 'org.example.myapp' does not read it
```

I found issue #60 describing a workaround to this. However, wouldn't it be a better solution if `jssc` was a Java module itself, i.e. declared its own `module-info.java`?

**Comment by tresf** [comment]
> wouldn't it be a better solution if jssc was a Java module itself, i.e. declared its own `module-info.java`?

Sure!

**Comment by pietrygamat** [comment]
Adding this would require the project to be compiled with jdk 9+, and to make sure the backwards comatibility with jre6 is preserved, some significant changes should be made in pom.xml. I can offer my help, but first I need some clarification:
Should it be assumed that the library still can be built with jdk7+ for those working on it locally, or can things be simplified, and from now on building the library requires jdk9+ (or even explicitly 11)?

**Comment by tresf** [comment]
> or can things be simplified

It's my opinion that the simpler the code, the better.   I don't think the code is complex now (the build system is, a bit).

**Comment by tresf** [comment]
@pietrygamat can you help summarize what's needed to close this out?  I'm not very familiar with the module system, but we're nearing a new release and as far as I understand the build system is ready with these changes.

**Comment by pietrygamat** [comment]
Build the release **with JDK11** and publish it, I guess. Users depending on artifacts from dependency management systems will be able to get the jar with module support.

**Comment by tresf** [comment]
@pietrygamat perfect, thanks.  @GMKennedy and I will build with JDK11 and then we'll close when #104 is merged then. :). Note, I've placed some comments in slack about fixing some compiler warnings before release.  They aren't directly related to this, but since they're a result of a newer compiler your thoughts are welcome. 🍻

**Comment by tresf** [comment]
Ok, I think this is directly related.... to suppress the compiler warnings the only combination I've found to work is:
```diff
+ @SuppressWarnings({ "requires-automatic", "requires-transitive-automatic" })
  open module jssc {
-     requires org.scijava.nativelib;
+     requires transitive org.scijava.nativelib;
      exports jssc;
  }
```

@pietrygamat I'm going to add this to #105  branch, merge into `master` today but suppressing these is frowned upon feel free to take them back out.
