### ISSUE TITLE
Won't work on Turkish Windows

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#80]
Investigation points to upstream; see also https://github.com/scijava/native-lib-loader/issues/39.

**Comment by invisible66** [comment]
Any solution?

**Comment by tresf** [comment]
@invisible66 we have had no luck getting this code merged from the native-lib-loader project.  We have already provided the patch but the project has not merged our fix.  A very crude workaround is available here: https://github.com/qzind/tray/commit/d376835245460218cbc3077237d814d397e7df18.  We will likely remove the native-lib-loader project or at the very least, build our own copy from a fork.

**Comment by invisible66** [comment]
Thanks for quick reply..

**Comment by tresf** [comment]
Looks like a bump is all that was needed.  Thanks scijava team! https://github.com/scijava/native-lib-loader/pull/40#issuecomment-878487884.

I'll bump this dependency soon.  We're working on a new release and this patch will be part of it.
